name: 📦 Build crawl4ai Docker Image and push to Docker Hub

on:
  workflow_call:
    inputs:
      crawl4ai_version:
        description: 'crawl4ai version to build. Example: 1.0.0'
        required: true
        type: string
      next_version_suffix:
        description: 'Next version suffix to compare with the new release. Example: 0'
        required: false
        type: string
      platform:
        description: 'Target platform (e.g., linux/amd64 or linux/arm64)'
        required: false
        default: 'linux/amd64'
        type: string
  workflow_dispatch:
    inputs:
      crawl4ai_version:
        description: 'crawl4ai version to build. Example: 1.0.0'
        required: true
        type: string
      next_version_suffix:
        description: 'Next version suffix to compare with the new release. Example: 0'
        required: false
        type: string
      platform:
        description: 'Target platform (e.g., linux/amd64 or linux/arm64)'
        required: false
        default: 'linux/amd64'
        type: string

jobs:
  build-push-docker-image:
    name: 🐳 Build and push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Clone crawl4ai repository
        run: git clone https://github.com/unclecode/crawl4ai.git
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: crawl4ai/deploy
          push: true
          tags: tinod/crawl4ai:${{ inputs.crawl4ai_version }}${{ inputs.next_version_suffix }},tinod/crawl4ai:latest
          platforms: ${{ inputs.platform }}

  create-release:
    name: 🏷️ Create GitHub Release
    needs: build-push-docker-image
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: crawl4ai@${{ inputs.crawl4ai_version }}${{ inputs.next_version_suffix }}

  notify-new-release:
    name: 💬 Notify new image release in Slack
    needs: build-push-docker-image
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.RELEASE_NOTIFICATION__SLACK_WEBHOOK_URL }}
        with:
          webhook-type: webhook-trigger
          payload: |
            channel: #it
            text: "New crawl4ai Image was pushed with version ${{ inputs.crawl4ai_version }}${{ inputs.next_version_suffix }}. :tada:"
